### ISSUE TITLE
Unable to debug docker builds, need output of commands e.g. --progress=plain

### ISSUE THREAD

**Issue by nightflight-dk** [Azure/azureml-assets#1034]
### Things you liked

ability to come in with my own docker file for the environment

### Things you didn't like

being unable to debug any errors, because someone decided to hide the output of RUN commands

### Suggestions

docker build **--progress=plain**

### Addition information

Multiple BizApps scenarios blocked, please prioritize.

**Comment by vizhur** [comment]
Thank you @nightflight-dk for the feedback. AzureML is leveraging ACR tasks that perform an image build, we can see if we can configure those for better experience. If your issue is related to pip timeouts, that is unlikely going to solve it as it comes from how nested dependencies are handling subprocess outputs (docker>conda>pip). If you can share an example what you think can be improved please share it.
